server:
  port: 80

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: api-gateway
  main:
    web-application-type: reactive
  application:
    name: spring-cloud-config-server
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9090
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/auth

        - id: user-service
          uri: http://localhost:9091
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: userCircuitBreaker
                fallbackUri: forward:/fallback/user

        - id: post-service
          uri: http://localhost:9092
          predicates:
            - Path=/post/**
          filters:
            - name: CircuitBreaker
              args:
                name: postCircuitBreaker
                fallbackUri: forward:/fallback/post

      default-filters:
        - RewritePath=/?(?<segment>.*), /$\{segment}