server:
  port: 9090

spring:
  security:
    user:
      name: enes
      password: 1234

  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/AuthDb
    username: postgres
    password: 1234

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update

rabbitmq:
  auth-exchange: authExchange
  register-queue: registerQueue
  register-bindingKey: registerBindingKey
  activeStatus-queue: activeStatusQueue
  activeStatus-bindingKey: activeStatusBindingKey
  sendMail-queue: sendMailQueue
  sendMail-bindingKey: sendMailBindingKey