server:
  port: 9093

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: mail-service

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user

  mail:
    host: smtp.gmail.com
    port: 587
    username: enesiyidil16@gmail.com
    password: daax cupn kntt jxgz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

rabbitmq:
  auth-exchange: authExchange
  sendMail-queue: sendMailQueue
  sendMail-bindingKey: sendMailBindingKey