server:
  port: 9091

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: userdb
      username: defaultUser
      password: bilge!123

    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user

  cache:
    type: redis


rabbitmq:
  auth-exchange: authExchange
  register-queue: registerQueue
  register-bindingKey: registerBindingKey
  activeStatus-queue: activeStatusQueue
  activeStatus-bindingKey: activeStatusBindingKey
  elastic-exchange: authExchange
  elastic-queue: elasticQueue
  elastic-bindingKey: elasticBindingKey

feign:
  auth: http://localhost:9090/auth